version: '2'
services:
  nginx-reverse:
    restart: always
    container_name: smartmoney-reverse-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/logs
      - ./conf/nginx:/etc/nginx/conf.d/
  
  haproxy:
    restart: always
    container_name: smartmoney-reverse-haproxy
    image: haproxy:latest
    ports:
      - "7999:7999"
      - "8098:8098"
      - "8087:8087"
      - "8099:8099"
      - "4369:4369"
      - "6000-6001:6000-6001"
    volumes:
      - ./conf/haproxy:/usr/local/etc/haproxy/
      
