version: '2'
services:
  nginx-proxy:
    restart: always
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./logs:/logs
      - ./conf:/etc/nginx/conf.d/
      - /vhosts/yellowpages/dist:/yellowpages
      - /vhosts/exchange:/exchange
